### ISSUE TITLE
Suspisious TOB oxgyen:dissolved:saturation units

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#14]
## Suspicious units
The following files present a dissolved:oxygen:saturation in [mL/L] the values within the range ~ [60 -120] which is more alligned with the more commonly used units for this parameter of saturation in %
www.waterproperties.ca/osd_data_archive/Cruise_Data/2007/2007-011/Underway/2007-011-0001.tob
www.waterproperties.ca/osd_data_archive/Cruise_Data/2007/2007-011/Underway/2007-011-0002.tob
www.waterproperties.ca/osd_data_archive/Cruise_Data/2007/2007-011/Underway/2007-011-0003.tob

**Comment by guanlu129** [comment]
The units should be %. We've fixed the units and updated the files.

**Comment by JessyBarrette** [comment]
Awesome I will then close this issue too!
