### ISSUE TITLE
IOS TOB Variable Vocabulary

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#17]
A few variables are missing either unit within the original file or related vocabulary:
related dataset https://pac-dev2.cioos.org/erddap/tabledap/IOS_TOB.html

related to HakaiInstitute/cioos-pacific-erddap-public#20 

## Missing Units

- [x] flow_rate (units = n/a):  ~[159 files list](https://github.com/HakaiInstitute/cioos-pacific-erddap/files/10958633/IOS_TOB_flow_rate_unitless.txt)

## Unknown BODC vocabulary 

- [x] Temperature:Lab [deg C (ITS90)]
- [x] Temperature:Intake [deg C (ITS90)]
- [x] flow_rate [L/min]
- [x] flow_rate_fl [L/min]

## Temperature data
A number of temperature-related variables were detected and I'm wondering if there are any related variables ex
https://www.waterproperties.ca/osd_data_archive/Cruise_Data/2018/2018-039/Underway/2018-039-0001.tob

**Comment by JessyBarrette** [comment]
@guanlu129 regarding the flow_rates, I suspect all the variables including the ones with no units are all L/min. 

Here are the min-max values associated with each variable ([here](https://pac-dev2.cioos.org/erddap/tabledap/IOS_TOB.html?time%2Cflow_rate_fl%2C&.draw=markers&.marker=5%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff)):
<img width="1071" alt="Screenshot 2023-04-12 at 4 16 39 PM" src="https://user-images.githubusercontent.com/30420025/231574539-38a1afe4-ccbd-4590-8c09-f8d50c18157a.png">

### Figures
[flow_rate](https://pac-dev2.cioos.org/erddap/tabledap/IOS_TOB.graph?time%2Cflow_rate%2C&.draw=markers&.marker=5%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff) [L/min]
![image](https://user-images.githubusercontent.com/30420025/231573806-4fe74291-6d0c-42fb-a397-c3029cdcc597.png)

[flow_rate](https://pac-dev2.cioos.org/erddap/tabledap/IOS_TOB.graph?time%2Cflow_rate_no_units%2C&.draw=markers&.marker=5%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff)
![image](https://user-images.githubusercontent.com/30420025/231574100-0461b465-351b-4104-a534-bc9d924db9ee.png)

[flow_rate_fl](https://pac-dev2.cioos.org/erddap/tabledap/IOS_TOB.graph?time%2Cflow_rate_fl%2C&.draw=markers&.marker=5%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff)
![image](https://user-images.githubusercontent.com/30420025/231574384-68216584-86a3-4863-93c9-c0e286f2d51c.png)

**Comment by guanlu129** [comment]
Would agree - we could make this assumption to assign L/min to measurements without a unit.

**Comment by JessyBarrette** [comment]
@guanlu129 Sounds good to me! Let's default units for flow_rate to L/min for TOB files then

**Comment by guanlu129** [comment]
Unknown BODC code:  
Temperature:Lab [deg C (ITS90)]   **CDTAZZ01**
 Temperature:Intake [deg C (ITS90)]   **TEMPSZ01**
 flow_rate [L/min]   **INFLTF01**
 flow_rate_fl [L/min]   **INFLTF01**

**Comment by guanlu129** [comment]
Unknown BODC code:
Temperature:Lab [deg C (ITS90)] TEMPSZ01
Temperature:Intake [deg C (ITS90)] TEMPTC01
flow_rate [L/min] INFLTF01
flow_rate_fl [L/min] INFLTF01

**Comment by JessyBarrette** [comment]
Awesome thanks @guanlu129 I can now close this issue
