### ISSUE TITLE
IOS TOB Duplicated variable 

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#18]
Some IOS TOB files contain duplicated variables Temperature:Lab (
example www.waterproperties.ca/osd_data_archive/Cruise_Data/2008/2008-010/Underway/2008-010-0002.tob)

|Column|          ios_name         | units|
|----|----|---|
|3|  Temperature:Lab | deg C (ITS90)|
|4|  Temperature:Lab | deg C (ITS90)|

By default the IOS conversion to NetCDF will only consider the first column. 

This issue is related to the following files:
- www.waterproperties.ca/osd_data_archive/Cruise_Data/2008/2008-010/Underway/2008-010-0002.tob
- www.waterproperties.ca/osd_data_archive/Cruise_Data/2016/2016-062/Underway/2016-062-0001.tob
- www.waterproperties.ca/osd_data_archive/Cruise_Data/2016/2016-062/Underway/2016-062-0002.tob
- www.waterproperties.ca/osd_data_archive/Cruise_Data/2016/2016-062/Underway/2016-062-0003.tob
- www.waterproperties.ca/osd_data_archive/Cruise_Data/2016/2016-062/Underway/2016-062-0004.tob

**Comment by guanlu129** [comment]
We've corrected the five TSG files mentioned.

**Comment by JessyBarrette** [comment]
Sounds good. Let's close that issue then!
