### ISSUE TITLE
Should this repository live on the cioos-siooc github page

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#28]
Since this repository essentially manages all the different datasets related to the cioos-siooc datasets in development and is served via ERDDAP on data.cioospacific.ca. Should we host that repository on cioos-siooc

@raytula @pramod-thupaki @n-a-t-e 

Let me know your thoughts, it's not a big deal to move it all there, we just did the whole process to move from 

https://github.com/HakaiInstitute/cioos-pacific-erddap  to https://github.com/HakaiInstitute/cioos-pacific-erddap-public

We can certainly move it all to cioos very easily.

**Comment by raytula** [comment]
I was wondering the same thing.  Yes, it sounds to me like this repo should be in the CIOOS GitHub org.

**Comment by JessyBarrette** [comment]
It's moved now :)
