### ISSUE TITLE
[Issue]: IOS_UBC_Profiles - Flag values in data

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#53]
### Level

High

### Issue Description

Some UBC files contain flag values -9.99 that aren't appropriately defined within the header:

This seems to be related to 
SSALST01 ~ 77 files
https://pac-dev2.cioos.org/erddap/tabledap/IOS_UBC_profiles.htmlTable?profile%2Cfilename%2CSSALST01&time%3E=1951-05-16T15%3A42%3A00Z&time%3C=1989-12-20T06%3A40%3A00Z&SSALST01%3C=0&distinct()

PSALST01 ~ 10 files
https://pac-dev2.cioos.org/erddap/tabledap/IOS_UBC_profiles.htmlTable?profile%2Cfilename%2CPSALST01&time%3E=1951-05-16T15%3A42%3A00Z&time%3C=1989-12-20T06%3A40%3A00Z&PSALST01%3C=0&distinct()

### Issue Solution

Since we can't modify those historical files, we may have to replace by NaN during the conversion the flag values.

**Comment by JessyBarrette** [comment]
This is issue is now handle by the conversion scrip which will replace suspicious values -9.99, -99.9, -99.0 etc by NaN

**Comment by guanlu129** [comment]
Cannot open the links below

SSALST01 ~ 77 files
https://pac-dev2.cioos.org/erddap/tabledap/IOS_UBC_profiles.htmlTable?profile%2Cfilename%2CSSALST01&time%3E=1951-05-16T15%3A42%3A00Z&time%3C=1989-12-20T06%3A40%3A00Z&SSALST01%3C=0&distinct()

PSALST01 ~ 10 files
https://pac-dev2.cioos.org/erddap/tabledap/IOS_UBC_profiles.htmlTable?profile%2Cfilename%2CPSALST01&time%3E=1951-05-16T15%3A42%3A00Z&time%3C=1989-12-20T06%3A40%3A00Z&PSALST01%3C=0&distinct()
