### ISSUE TITLE
[Issue]: IOS_TOB - "flow rate" variable

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#55]
### Level

Low

### Issue Description

One unique file contains a variable called "flow rate" instead of "Flow_Rate". This is a minor issue we could always ingest it but I feel it's an easy correction to fix directely at the [source file ](https://www.waterproperties.ca/osd_data_archive/Cruise_Data/2019/2019-001/Underway/2019-001-0220-000002.tob) 
```
/data/ios_raw_files/cruise_data/2019/2019-001/Underway/2019-001-0220-000002.tob
```

### Issue Solution

Fix source file

**Comment by guanlu129** [comment]
Resolved? Didn't see any "flow_rate" in this file.

**Comment by JessyBarrette** [comment]
I guess so that's good then We can close that issue
