### ISSUE TITLE
[Issue]: IOS_CTD_profiles - Missing Location

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#61]
### Level

Low

### Issue Description

The following files present likely a bad location:
- https://www.waterproperties.ca/osd_data_archive/Cruise_Data/1991/1991-099/CTD/1991-099-0029.ctd
- https://www.waterproperties.ca/osd_data_archive/Cruise_Data/1991/1991-099/CTD/1991-099-0036.ctd

**Comment by guanlu129** [comment]
seems correct after checking the events before and after the target profiles.

**Comment by JessyBarrette** [comment]
So we can assume that those specific casts are near the north pole?

**Comment by JessyBarrette** [comment]
Sounds good then! We can then close that issue :)
