### ISSUE TITLE
[Issue]: IOS_CTD_profiles - PAR related variables mapping to vocabularies

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-pacific-erddap#63]
### Level

Mid

## PAR mapping
The different `PAR` related variables observed available within IOS datasets are as of now mapped to different terms in BIO  equivalent datasets. 

Since both organizations are likely using the same instruments, I'm wondering what is the most appropriate. 

### PAR in water 
As of now the PAR in water-related variables: `par`, `par:1`, and `par:ctd` are mapped to the following vocabulary terms:

|office|standard_name| sdn_parameter_urn| sdn_parameter_name|
|---|---|---|---|
|IOS| |SDN:P01::SCIRR4PI|4-pi scalar irradiance as photons of electromagnetic radiation (PAR wavelengths) in the water body by 4-pi scalar radiometer|
|BIO| downwelling_photosynthetic_photon_spherical_irradiance_in_sea_water|SDN:P01::IRRDUV01|Downwelling vector irradiance as photons of electromagnetic radiation (PAR wavelengths) in the water body by cosine-collector radiometer|

I can't find appropriate cf term related to this. 

### Surface reference `par:reference`

|Office|standard_name| sdn_parameter_urn| sdn_parameter_name|
|---|---|---|---|
|IOS| | SDN:P01::IRRDSV01|Downwelling vector irradiance as photons of electromagnetic radiation (PAR wavelengths) in the atmosphere by cosine-collector radiometer|
|BIO|surface_downwelling_photosynthetic_photon_spherical_irradiance_in_sea_water|SDN:P01::IRRDSV01|Downwelling vector irradiance as photons of electromagnetic radiation (PAR wavelengths) in the atmosphere by cosine-collector radiometer|

**Comment by guanlu129** [comment]
Should go with SDN:P01::IRRDSV01.

References:
https://www.bco-dmo.org/dataset-instrument/648991
http://vocab.nerc.ac.uk/collection/L22/current/TOOL0074/

**Comment by JessyBarrette** [comment]
Thanks @guanlu129 I will add that

**Comment by JessyBarrette** [comment]
Ok looks like the instrument http://vocab.nerc.ac.uk/collection/L22/current/TOOL0074/ is matched to the BODC term P01 = http://vocab.nerc.ac.uk/collection/P01/current/IRRDUV01/

We will them rename those PAR variables to this term instead, this is the same used by BIO

**Comment by guanlu129** [comment]
Sounds good!
